-- Constants

ListFish = {"Abaia","Ahtapot","Alabaligi","Armored Pisces","Bastore Bream","Bastore Sardine","Bastore Sweeper","Betta","Bhefhel Marlin","Bibiki Urchin","Bibikibo","Black Eel","Black Ghost","Black Sole","Bladefish","Blindfish","Bluetail","Brass Loach","Ca Cuong","Caedarva Frog","Cave Cherax","Cheval Salmon","Cobalt Jellyfish","Cone Calamary","Copper Frog","Coral Butterfly","Crayfish","Crescent Fish","Crystal Bass","Dark Bass","Denizanasi","Dil","Elshimo Frog","Elshimo Newt","Emperor Fish","Fat Greedie","Forest Carp","Garpike","Gavial Fish","Gerrothorax","Giant Catfish","Giant Chirai","Giant Donko","Gigant Octopus","Gigant Squid","Gold Carp","Gold Lobster","Greedie","Grimmonite","Gugru Tuna","Gugrusaurus","Gurnard","Hamsi","Icefish","Istakoz","Istavrit","Istiridye","Jungle Catfish","Kalamar","Kalkanbaligi","Kaplumbaga","Kayabaligi","Kilicbaligi","Lakerda","Lik","Lungfish","Matsya","Megalodon","Mercanbaligi","Moat Carp","Mola Mola","Monke-Onke","Moorish Idol","Morinabaligi","Muddy Siredon","Nebimonite","Noble Lady","Nosteau Herring","Ogre Eel","Phanauet Newt","Pipira","Pirarucu","Pterygotus","Quus","Red Bubble-Eye","Red Terrapin","Rhinochimera","Ryugu Titan","Sandfish","Sazanbaligi","Sea Zombie","Shall Shell","Shining Trout","Silver Shark","Takitaro","Tavnazian Goby","Three-eyed Fish","Tiger Cod","Tiny Goldfish","Titanic Sawfish","Titanictus","Tricolored Carp","Tricorn","Trilobite","Trumpet Shell","Turnabaligi","Uskumru","Veydal Wrasse","Vongola Clam","Yayinbaligi","Yellow Globe","Yilanbaligi","Zafmlug Bass","Zebra Eel"};

FishLvls = {["abaia"] = 104,["ahtapot"] = 90,["alabaligi"] = 37,["armored pisces"] = 108,["bastore bream"] = 86,["bastore sardine"] = 9,["bastore sweeper"] = 12,["betta"] = 68,["bhefhel marlin"] = 61,["bibiki urchin"] = 3,["bibikibo"] = 32,["black eel"] = 47,["black ghost"] = 88,["black sole"] = 96,["bladefish"] = 71,["blindfish"] = 28,["bluetail"] = 55,["brass loach"] = 42,["ca cuong"] = 73,["caedarva frog"] = 30,["cave cherax"] = 109,["cheval salmon"] = 21,["cobalt jellyfish"] = 5,["cone calamary"] = 48,["copper frog"] = 16,["coral butterfly"] = 40,["crayfish"] = 7,["crescent fish"] = 69,["crystal bass"] = 35,["dark bass"] = 33,["denizanasi"] = 6,["dil"] = 96,["elshimo frog"] = 30,["elshimo newt"] = 59,["emperor fish"] = 94,["fat greedie"] = 24,["forest carp"] = 20,["garpike"] = 83,["gavial fish"] = 81,["gerrothorax"] = 100,["giant catfish"] = 31,["giant chirai"] = 110,["giant donko"] = 50,["gigant octopus"] = 80,["gigant squid"] = 91,["gold carp"] = 56,["gold lobster"] = 46,["greedie"] = 14,["grimmonite"] = 90,["gugru tuna"] = 41,["gugrusaurus"] = 110,["gurnard"] = 26,["hamsi"] = 9,["icefish"] = 49,["istakoz"] = 46,["istavrit"] = 40,["istiridye"] = 53,["jungle catfish"] = 80,["kalamar"] = 48,["kalkanbaligi"] = 100,["kaplumbaga"] = 53,["kayabaligi"] = 75,["kilicbaligi"] = 61,["lakerda"] = 41,["lik"] = 110,["lungfish"] = 31,["matsya"] = 100,["megalodon"] = 87,["mercanbaligi"] = 86,["moat carp"] = 11,["mola mola"] = 100,["monke-onke"] = 51,["moorish idol"] = 31,["morinabaligi"] = 94,["muddy siredon"] = 18,["nebimonite"] = 27,["noble lady"] = 66,["nosteau herring"] = 39,["ogre eel"] = 35,["phanauet newt"] = 4,["pipira"] = 29,["pirarucu"] = 89,["pterygotus"] = 99,["quus"] = 19,["red bubble-eye"] = 109,["red terrapin"] = 53,["rhinochimera"] = 65,["ryugu titan"] = 108,["sandfish"] = 50,["sazanbaligi"] = 56,["sea zombie"] = 100,["shall shell"] = 53,["shining trout"] = 37,["silver shark"] = 76,["takitaro"] = 100,["tavnazian goby"] = 75,["three-eyed fish"] = 79,["tiger cod"] = 29,["tiny goldfish"] = 20,["titanic sawfish"] = 100,["titanictus"] = 100,["tricolored carp"] = 27,["tricorn"] = 100,["trilobite"] = 61,["trumpet shell"] = 63,["turnabaligi"] = 100,["uskumru"] = 55,["veydal wrasse"] = 35,["vongola clam"] = 52,["yayinbaligi"] = 31,["yellow globe"] = 17,["yilanbaligi"] = 47,["zafmlug bass"] = 43,["zebra eel"] = 71};

ZoneType = {[0] = 1,[26] = 1,[32] = 1,[48] = 1,[50] = 1,[70] = 1,[71] = 1,[80] = 1,[87] = 1,[94] = 1,[189] = 1,[199] = 1,[214] = 1,[219] = 1,[230] = 1,[231] = 1,[232] = 1,[233] = 1,[234] = 1,[235] = 1,[236] = 1,[237] = 1,[238] = 1,[239] = 1,[240] = 1,[241] = 1,[242] = 1,[243] = 1,[244] = 1,[245] = 1,[246] = 1,[247] = 1,[248] = 1,[249] = 1,[250] = 1,[251] = 1,[252] = 1,[256] = 1,[257] = 1,[280] = 1,[284] = 1,[285] = 1};

ListItem = {"Gil","Arrowwood Log","Bugbear Mask","Copper Ring","Coral Fragment","Damp Scroll","Fish Scale Shield","Lamp Marimo","Moblin Mask","Mythril Dagger","Mythril Sword","Norg Shell","Pamtam Kelp","Ripped Cap","Rusty Bucket","Rusty Cap","Rusty Greatsword","Rusty Leggings","Rusty Pick","Rusty Subligar","Silver Ring"};

ListAll = {"Abaia","Ahtapot","Alabaligi","Armored Pisces","Bastore Bream","Bastore Sardine","Bastore Sweeper","Betta","Bhefhel Marlin","Bibiki Urchin","Bibikibo","Black Eel","Black Ghost","Black Sole","Bladefish","Blindfish","Bluetail","Brass Loach","Ca Cuong","Caedarva Frog","Cave Cherax","Cheval Salmon","Cobalt Jellyfish","Cone Calamary","Copper Frog","Coral Butterfly","Crayfish","Crescent Fish","Crystal Bass","Dark Bass","Denizanasi","Dil","Elshimo Frog","Elshimo Newt","Emperor Fish","Fat Greedie","Forest Carp","Garpike","Gavial Fish","Gerrothorax","Giant Catfish","Giant Chirai","Giant Donko","Gigant Octopus","Gigant Squid","Gold Carp","Gold Lobster","Greedie","Grimmonite","Gugru Tuna","Gugrusaurus","Gurnard","Hamsi","Icefish","Istakoz","Istavrit","Istiridye","Jungle Catfish","Kalamar","Kalkanbaligi","Kaplumbaga","Kayabaligi","Kilicbaligi","Lakerda","Lik","Lungfish","Matsya","Megalodon","Mercanbaligi","Moat Carp","Mola Mola","Monke-Onke","Moorish Idol","Morinabaligi","Muddy Siredon","Nebimonite","Noble Lady","Nosteau Herring","Ogre Eel","Phanauet Newt","Pipira","Pirarucu","Pterygotus","Quus","Red Bubble-Eye","Red Terrapin","Rhinochimera","Ryugu Titan","Sandfish","Sazanbaligi","Sea Zombie","Shall Shell","Shining Trout","Silver Shark","Takitaro","Tavnazian Goby","Three-eyed Fish","Tiger Cod","Tiny Goldfish","Titanic Sawfish","Titanictus","Tricolored Carp","Tricorn","Trilobite","Trumpet Shell","Turnabaligi","Uskumru","Veydal Wrasse","Vongola Clam","Yayinbaligi","Yellow Globe","Yilanbaligi","Zafmlug Bass","Zebra Eel","Gil","Arrowwood Log","Bugbear Mask","Copper Ring","Coral Fragment","Damp Scroll","Fish Scale Shield","Lamp Marimo","Moblin Mask","Mythril Dagger","Mythril Sword","Norg Shell","Pamtam Kelp","Ripped Cap","Rusty Bucket","Rusty Cap","Rusty Greatsword","Rusty Leggings","Rusty Pick","Rusty Subligar","Silver Ring"};

SkillTypes = {[48]="Fishing",[49]="Woodworking",[50]="Smithing",[51]="Goldsmithing",[52]="Clothcraft",[53]="Leathercraft",[54]="Bonecraft",[55]="Alchemy",[56]="Cooking",[57]="Synergy",[58]="Rid",[59]="Dig"};

return {
   ListFish = ListFish,
	FishLvls = FishLvls,
	ZoneType = ZoneType,
   ListItem = ListItem,
	ListAll  = ListAll,
   SkillTypes = SkillTypes
}