-- Constants

ListFish = {"Abaia","Ahtapot","Alabaligi","Armored Pisces","Bastore Bream","Bastore Sardine","Bastore Sweeper","Betta","Bhefhel Marlin","Bibiki Urchin","Bibikibo","Black Eel","Black Ghost","Black Sole","Bladefish","Blindfish","Bluetail","Brass Loach","Ca Cuong","Caedarva Frog","Cave Cherax","Cheval Salmon","Cobalt Jellyfish","Cone Calamary","Copper Frog","Coral Butterfly","Crayfish","Crescent Fish","Crystal Bass","Dark Bass","Denizanasi","Dil","Elshimo Frog","Elshimo Newt","Emperor Fish","Fat Greedie","Forest Carp","Garpike","Gavial Fish","Gerrothorax","Giant Catfish","Giant Chirai","Giant Donko","Gigant Octopus","Gigant Squid","Gold Carp","Gold Lobster","Greedie","Grimmonite","Gugru Tuna","Gugrusaurus","Gurnard","Hamsi","Icefish","Istakoz","Istavrit","Istiridye","Jungle Catfish","Kalamar","Kalkanbaligi","Kaplumbaga","Kayabaligi","Kilicbaligi","Lakerda","Lik","Lungfish","Matsya","Megalodon","Mercanbaligi","Moat Carp","Mola Mola","Monke-Onke","Moorish Idol","Morinabaligi","Muddy Siredon","Nebimonite","Noble Lady","Nosteau Herring","Ogre Eel","Phanauet Newt","Pipira","Pirarucu","Pterygotus","Quus","Red Bubble-Eye","Red Terrapin","Rhinochimera","Ryugu Titan","Sandfish","Sazanbaligi","Sea Zombie","Shall Shell","Shining Trout","Silver Shark","Takitaro","Tavnazian Goby","Three-eyed Fish","Tiger Cod","Tiny Goldfish","Titanic Sawfish","Titanictus","Tricolored Carp","Tricorn","Trilobite","Trumpet Shell","Turnabaligi","Uskumru","Veydal Wrasse","Vongola Clam","Yayinbaligi","Yellow Globe","Yilanbaligi","Zafmlug Bass","Zebra Eel"};

FishLvls = {["abaia"] = 104,["ahtapot"] = 90,["alabaligi"] = 37,["armored pisces"] = 108,["bastore bream"] = 86,["bastore sardine"] = 9,["bastore sweeper"] = 12,["betta"] = 68,["bhefhel marlin"] = 61,["bibiki urchin"] = 3,["bibikibo"] = 32,["black eel"] = 47,["black ghost"] = 88,["black sole"] = 96,["bladefish"] = 71,["blindfish"] = 28,["bluetail"] = 55,["brass loach"] = 42,["ca cuong"] = 73,["caedarva frog"] = 30,["cave cherax"] = 109,["cheval salmon"] = 21,["cobalt jellyfish"] = 5,["cone calamary"] = 48,["copper frog"] = 16,["coral butterfly"] = 40,["crayfish"] = 7,["crescent fish"] = 69,["crystal bass"] = 35,["dark bass"] = 33,["denizanasi"] = 6,["dil"] = 96,["elshimo frog"] = 30,["elshimo newt"] = 59,["emperor fish"] = 94,["fat greedie"] = 24,["forest carp"] = 20,["garpike"] = 83,["gavial fish"] = 81,["gerrothorax"] = 100,["giant catfish"] = 31,["giant chirai"] = 110,["giant donko"] = 50,["gigant octopus"] = 80,["gigant squid"] = 91,["gold carp"] = 56,["gold lobster"] = 46,["greedie"] = 14,["grimmonite"] = 90,["gugru tuna"] = 41,["gugrusaurus"] = 110,["gurnard"] = 26,["hamsi"] = 9,["icefish"] = 49,["istakoz"] = 46,["istavrit"] = 40,["istiridye"] = 53,["jungle catfish"] = 80,["kalamar"] = 48,["kalkanbaligi"] = 100,["kaplumbaga"] = 53,["kayabaligi"] = 75,["kilicbaligi"] = 61,["lakerda"] = 41,["lik"] = 110,["lungfish"] = 31,["matsya"] = 100,["megalodon"] = 87,["mercanbaligi"] = 86,["moat carp"] = 11,["mola mola"] = 100,["monke-onke"] = 51,["moorish idol"] = 31,["morinabaligi"] = 94,["muddy siredon"] = 18,["nebimonite"] = 27,["noble lady"] = 66,["nosteau herring"] = 39,["ogre eel"] = 35,["phanauet newt"] = 4,["pipira"] = 29,["pirarucu"] = 89,["pterygotus"] = 99,["quus"] = 19,["red bubble-eye"] = 109,["red terrapin"] = 53,["rhinochimera"] = 65,["ryugu titan"] = 108,["sandfish"] = 50,["sazanbaligi"] = 56,["sea zombie"] = 100,["shall shell"] = 53,["shining trout"] = 37,["silver shark"] = 76,["takitaro"] = 100,["tavnazian goby"] = 75,["three-eyed fish"] = 79,["tiger cod"] = 29,["tiny goldfish"] = 20,["titanic sawfish"] = 100,["titanictus"] = 100,["tricolored carp"] = 27,["tricorn"] = 100,["trilobite"] = 61,["trumpet shell"] = 63,["turnabaligi"] = 100,["uskumru"] = 55,["veydal wrasse"] = 35,["vongola clam"] = 52,["yayinbaligi"] = 31,["yellow globe"] = 17,["yilanbaligi"] = 47,["zafmlug bass"] = 43,["zebra eel"] = 71};

ZoneType = {[0] = 1,[26] = 1,[32] = 1,[48] = 1,[50] = 1,[70] = 1,[71] = 1,[80] = 1,[87] = 1,[94] = 1,[189] = 1,[199] = 1,[214] = 1,[219] = 1,[230] = 1,[231] = 1,[232] = 1,[233] = 1,[234] = 1,[235] = 1,[236] = 1,[237] = 1,[238] = 1,[239] = 1,[240] = 1,[241] = 1,[242] = 1,[243] = 1,[244] = 1,[245] = 1,[246] = 1,[247] = 1,[248] = 1,[249] = 1,[250] = 1,[251] = 1,[252] = 1,[256] = 1,[257] = 1,[280] = 1,[284] = 1,[285] = 1};

ListItem = {"Gil","Arrowwood Log","Bugbear Mask","Copper Ring","Coral Fragment","Damp Scroll","Fish Scale Shield","Lamp Marimo","Moblin Mask","Mythril Dagger","Mythril Sword","Norg Shell","Pamtam Kelp","Ripped Cap","Rusty Bucket","Rusty Cap","Rusty Greatsword","Rusty Leggings","Rusty Pick","Rusty Subligar","Silver Ring"};

ListAll = {"Abaia","Ahtapot","Alabaligi","Armored Pisces","Bastore Bream","Bastore Sardine","Bastore Sweeper","Betta","Bhefhel Marlin","Bibiki Urchin","Bibikibo","Black Eel","Black Ghost","Black Sole","Bladefish","Blindfish","Bluetail","Brass Loach","Ca Cuong","Caedarva Frog","Cave Cherax","Cheval Salmon","Cobalt Jellyfish","Cone Calamary","Copper Frog","Coral Butterfly","Crayfish","Crescent Fish","Crystal Bass","Dark Bass","Denizanasi","Dil","Elshimo Frog","Elshimo Newt","Emperor Fish","Fat Greedie","Forest Carp","Garpike","Gavial Fish","Gerrothorax","Giant Catfish","Giant Chirai","Giant Donko","Gigant Octopus","Gigant Squid","Gold Carp","Gold Lobster","Greedie","Grimmonite","Gugru Tuna","Gugrusaurus","Gurnard","Hamsi","Icefish","Istakoz","Istavrit","Istiridye","Jungle Catfish","Kalamar","Kalkanbaligi","Kaplumbaga","Kayabaligi","Kilicbaligi","Lakerda","Lik","Lungfish","Matsya","Megalodon","Mercanbaligi","Moat Carp","Mola Mola","Monke-Onke","Moorish Idol","Morinabaligi","Muddy Siredon","Nebimonite","Noble Lady","Nosteau Herring","Ogre Eel","Phanauet Newt","Pipira","Pirarucu","Pterygotus","Quus","Red Bubble-Eye","Red Terrapin","Rhinochimera","Ryugu Titan","Sandfish","Sazanbaligi","Sea Zombie","Shall Shell","Shining Trout","Silver Shark","Takitaro","Tavnazian Goby","Three-eyed Fish","Tiger Cod","Tiny Goldfish","Titanic Sawfish","Titanictus","Tricolored Carp","Tricorn","Trilobite","Trumpet Shell","Turnabaligi","Uskumru","Veydal Wrasse","Vongola Clam","Yayinbaligi","Yellow Globe","Yilanbaligi","Zafmlug Bass","Zebra Eel","Gil","Arrowwood Log","Bugbear Mask","Copper Ring","Coral Fragment","Damp Scroll","Fish Scale Shield","Lamp Marimo","Moblin Mask","Mythril Dagger","Mythril Sword","Norg Shell","Pamtam Kelp","Ripped Cap","Rusty Bucket","Rusty Cap","Rusty Greatsword","Rusty Leggings","Rusty Pick","Rusty Subligar","Silver Ring"};

ListBait = {"Crayfish Ball","Drill Calamary","Dwarf Pugil","Fly Lure","Frog Lure","Giant Shell Bug","Insect Ball","Little Worm","Lizard Lure","Lufaise Fly","Lugworm","Meatball","Minnow","Peeled Crayfish","Peeled Lobster","Robber Rig","Rogue Rig","Rotten Meat","Sabiki Rig","Sardine Ball","Shell Bug","Shrimp Lure","Sinking Minnow","Slice of Bluetail","Slice of Carp","Sliced Cod","Sliced Sardine","Trout Ball","Worm Lure"};

ListZone = {"Aht Urhgan Whitegate","Al Zahbi","Arrapago Reef","Aydeewa Subterrane","Bastok Markets","Bastok Markets [S]","Bastok Mines","Batallia Downs","Batallia Downs [S]","Beaucedine Glacier","Bhaflau Thickets","Bibiki Bay","Bostaunieux Oubliette","Boyahda Tree","Buburimu Peninsula","Caedarva Mire","Cape Teriggan","Carpenters' Landing","Castle Oztroja","Dangruf Wadi","Davoi","Delkfutt's Tower","Den of Rancor","Dragon's Aery","East Ronfaure","East Ronfaure [S]","East Sarutabaruta","Eastern Altepa Desert","Fei'Yin","Ghelsba Outpost","Giddeus","Grauberg [S]","Gusgen Mines","Gustav Tunnel","Heavens Tower","Jugner Forest","Jugner Forest [S]","Kazham","Korroloka Tunnel","Kuftal Tunnel","La Theine Plateau","La Vaule [S]","Labyrinth of Onzozo","Lower Jeuno","Lufaise Meadows","Mamook","Manaclipper","Metalworks","Mhaura","Misareaux Coast","Mount Zhayolm","Nashmau","Norg","North Gustaberg","North Gustaberg [S]","Northern San d'Oria","Oldton Movalpolos","Open sea route","Ordelle's Caves","Palborough Mines","Pashhow Marshlands","Pashhow Marshlands [S]","Phanauet Cannel","Phomiuna Aqueducts","Port Bastok","Port Jeuno","Port San d'Oria","Port Windurst","Purgonorgo Isle","Qufim Island","Quicksand Caves","Rabao","Ranguemont Pass","Ro'Maeve","Rolanberry Fields","Rolanberry Fields [S]","Ru'Aun Gardens","Sanctuary of Zi'Tah","Sauromugue Champaign","Sea Serpent Grotto","Selbina","Ship","Shrine of Ru'Avitau","Silver sea route","South Gustaberg","Talacca Cave","Tavnazian Safehold","Temple of Uggalepih","Valkurm Dunes","Vunkerl Inlet [S]","Wajaom Woodlands","West Ronfaure","West Sarutabaruta","West Sarutabaruta [S]","Western Altepa Desert","Windurst Walls","Windurst Waters","Windurst Waters [S]","Windurst Woods","Yhoator Jungle","Yughott Grotto","Yuhtunga Jungle","Zeruhn Mines"};

FishingGuide = {"Guild Test","Equipment","Messages 1","Messages 2","Skill: 0-11","Skill: 11-20","Skill: 20-33","Skill: 33-41","Skill: 41-55","Skill: 55-62","Skill: 62-67","Skill: 67-75","Skill: 75-96","Lu Shang's","Skill: 96-100","Next Steps","Useful Links"};

ListDetails = {};
ListDetails["Guild Test"] = " Level    Item Requested    Rank Acquired\n-----------------------------------------\n  8-10    Moat Carp         Recruit\n 18-20    Cheval Salmon     Initiate\n 28-30    Giant Catfish     Novice\n 38-40    Gugru Tuna        Apprentice\n 48-50    Monke-Onke        Journeyman\n 58-60    Bhefhel Marlin    Craftsman\n 68-70    Bladefish         Artisan\n 78-80    Three-eyed Fish   Adept\n 88-90    Gigant Squid      Veteran\n98-100    Tiger Shark       Expert";
ListDetails["Equipment"] = " *  Attire:\n\n    >  Fisherman\'s Tunica Set (This guide\n       relies on all 4 pieces from 20\n       onward. Sell some Moats to fund\n       initial costs.)\n\n *  Rods:\n\n    >  Hume Fishing Rod, Halcyon Fishing\n       Rod, Composite Fishing Rod,\n       Lu Shang\'s Fishing Rod\n\n *  Bait:\n\n    >  Insect Paste, Meatball\n\n *  Lures:\n\n    >  Sinking Minnow, Shrimp Lure,\n       Fly Lure, Robber Rig, Minnow,\n       Worm Lure, Frog Lure";
ListDetails["Messages 1"] = "Understanding what\'s on the end of your\nFishing Rod:\n\nMessages displayed upon getting a bite\nwill indicate the size and type of your\npotential catch as follows:\n\n *  Small fish: \"Something caught the hook!\"\n *  Large fish: \"Something caught the hook!!!\"\n *  Non-fish:   \"You feel something pulling\n                 at your line.\"\n *  Monsters:   \"Something clamps onto your\n                 line ferociously!\"";
ListDetails["Messages 2"] = "Additionally, you get a second line with\nyour \"gut feeling\" about the fish:\n\n    *  \"You have a good feeling about this\n        one!\" = The fish is 10 levels or\n        less higher than your skill+gear or\n        you\'re above its skill cap.\n\n    *  \"You have a bad/terrible feeling\n        about this one!\" = The fish is 10\n        levels or less higher than your\n		skill+gear or you\'re above its\n		skill cap but can possibly snap\n		your line or rod.\n\n    *  \"You\'re fairly sure you don\'t have\n        enough skill to reel this one in.\"\n        = The fish is 11+ levels above your\n        skill+gear. You can still reel it in\n        although you may be greeted with the\n        message \"your skill is too low to\n        reel this one in\". Note that on\n        WingsXI this message also ensures\n        there is a chance for your line to\n        snap regardless of what retail is\n        like (Private server nerf!).\n\n    *  \"Your keen angler\'s senses tell you\n        that this is the pull of X.\" = A\n        critical bite. You get Angler\'s\n        Discernment, the fish recovers less\n        stamina for incorrect button\n		presses, and most buttons will be\n		gold.\n\n    *  \"This strength... You get the sense\n        that you are on the verge of an epic\n        catch!\" = This has a chance to show\n        up when you\'re at 95+ skill and hook\n        a large fish. It usually means a\n		high level legendary fish, but has\n		a rare chance of showing up on lower\n		level fish. It doesn\'t change\n		anything about catching the fish.";
ListDetails["Skill: 0-11"] = "Target:         Moat Carp (11)\nLocation:       West Ronfaure\nBody of Water:  Knightwell\nSetup:          Hume Fishing Rod\n                Insect Paste\n\n\n *  Isolates Moat Carp at a 50%+ bite rate.";
ListDetails["Skill: 11-20"] = "Target:         Cheval Salmon (21)\nLocation:       East Ronfaure\nBody of Water:  Any River\nSetup:          Halcyon Fishing Rod\n                Fly Lure\n\n\n *  Be careful Shining Trout will snap your\n    line although they are easily identified\n    as \"You\'re fairly sure you don\'t have\n    enough skill to reel this one in.\"";
ListDetails["Skill: 20-33"] = "Target:         Dark Bass (33)\n                Shining Trout (37)\nLocation:       Carpenter's Landing\n                (North - Enter in from\n				 Northern San d'Oria)\nBody of Water:  River (Near the Dock)\nSetup:          Halcyon Fishing Rod\n                Insect Paste / Fly Lure\n\n\n *  Make sure you have all 4 pieces of the\n    fishing set to bridge the 10 lvl gap and\n    isolate dark bass with insect paste for\n    the first 3 lvls.";
ListDetails["Skill: 33-41"] = "Target:         Black Eel (47)\nLocation:       Zeruhn Mines\nBody of Water:  Pond or River\nSetup:          Halcyon Fishing Rod\n                Worm Lure\n\n\n *  Great skill ups and easily identifiable.\n    Fetch 2k a stack to NPCs.";
ListDetails["Skill: 41-55"] = "Target:         Bluetail (55)\n                Shall Shell (53)\nLocation:       Buburimu Peninsula\nBody of Water:  Ocean (K-8)\nSetup:          Halcyon Fishing Rod\n                Minnow / Robber Rig\n\n\n *  Slow to skill but worth a decent amount\n    of gil via NPC. Use a Robber Rig to\n    targetShall Shells also but cancel any\n    \"bad feelings\".";
ListDetails["Skill: 55-62"] = "Target:         Crescent Fish (69)\nLocation:       East Sarutabaruta\nBody of Water:  Lake Tepokalipuka\nSetup:          Halcyon Fishing Rod\n                Fly Lure\n\n\n *  Slow going but NPC well and stack.\n    Cancel any \"bad feelings\".";
ListDetails["Skill: 62-67"] = "Target:         Silver Shark (76)\nLocation:       Batallia Down\nBody of Water:  Ocean (North or South)\nSetup:          Halcyon Fishing Rod\n                Meatball\n\n\n *  Very good skill-ups but reduced bite\n    rate on Wings (16%%).";
ListDetails["Skill: 67-75"] = "Target:         Gavial Fish (81)\nLocation:       North Gustaberg\nBody of Water:  Drachenfall\n                (Run through Dangruf)\nSetup:          Composite Fishing Rod\n                Meatball / Minnow\n\n\n *  Very good skill-ups and 30%% bite rate.\n    Don\'t stack. Drop or do the legwork to\n    clean your inventory. Minnow is a lower\n    drop rate and will require you to cancel\n    \"bad feelings\".";
ListDetails["Skill: 75-96"] = "Target:         Black Sole (96)\nLocation:       Batallia Downs\nBody of Water:  Ocean (North or South)\nSetup:          Composite Fishing Rod\n                Sinking Minnow\n\n\n *  Wonderful Gil and 33%% bite rate. You\n    will lose a lot due to lack of skill\n    until 82. Once 82 you will continue to\n    lose some due to being too small for\n    a Composite Rod.Halcyon runs a high\n    chance of snapped lines and lost lures\n    so just use the Composite until you\n    acquire Lu Shang\'s.\n\n\nBy now you should have made enough gil to purchase a Lu Shang\'s Fishing Rod. Purchase or quest it.";
ListDetails["Lu Shang's"] = "Questing Lu Shang\'s Fast (834 Stacks total)\n\nSkill Level:    52+\nTarget:         Moat Cap (11)\n                Gold Carp (56)\nLocation:       Windurst Woods\nBody of Water:  Dhamel Pen (Bridge)\nSetup:          Halcyon Fishing Rod\n                Insect Paste\n\n\n *  Best bite rate I could find and you\n    can NPC the Gold Carps for a decent\n    amount of gil.\n\n *  Create a trade mule and keep that\n    character in it\'s mog house in Port\n    San d\'Oria.\n\n *  Log between accounts for quick\n    exchanges as you fill your inventory\n    on your main character.\n\n *  I could hit around 50ish stacks a day\n    if I really went hard. Casually, it\'ll\n    take most about a month to save up\n    only fishing them.\n\n *  3k a stack if you just want to buy it\n    (or) 2.6mil Gil if you buy them all.\n\n\nTime to finish skilling up!";
ListDetails["Skill: 96-100"] = "Target:         Armored Pisces (108)\nLocation:       Oldton Movalpolos\nBody of Water:  Center Pond\nSetup:          Lu Shang\'s Fishing Rod\n                Sinking Minnow\n\n\n *  Don\'t stack but will provide great\n    skill-ups to get you from 96 to 100.\n\n\nCongratulations! You are now a 100 Fisherman. This is all obtainable in just over a month.";
ListDetails["Next Steps"] = "1. Farm GP and collect the rare items and key\n   items from the guild.\n\n2. Complete quests up to \"Inside the Belly\"\n   for chances at multi-hit weapons rewards\n   and other rare items. (Needs\n   Implementation on Wings)\n\n3. Complete the \"Indomitable Spirit\" quest\n   for Ebisu Fishing Rod. (Needs\n   Implementation on Wings)\n\n4. Make endless amounts of Gil.";
ListDetails["Useful Links"] = "http://www.great-blue.jp/?lng=en\n\nhttps://ffxiclopedia.fandom.com/wiki/Category:Fishing/All_Recipes\n\nhttps://ffxiclopedia.fandom.com/wiki/Category%%3AFishing\n\nhttps://ffxiclopedia.fandom.com/wiki/Inside_the_Belly\n\nhttps://ffxiclopedia.fandom.com/wiki/Pirate%%27s_Chart_Ques";

SkillTypes = {[48]="Fishing",[49]="Woodworking",[50]="Smithing",[51]="Goldsmithing",[52]="Clothcraft",[53]="Leathercraft",[54]="Bonecraft",[55]="Alchemy",[56]="Cooking",[57]="Synergy",[58]="Rid",[59]="Dig"};

return {
   ListFish = ListFish,
	FishLvls = FishLvls,
	ZoneType = ZoneType,
   ListItem = ListItem,
	ListAll  = ListAll,
   ListBait = ListBait,
	ListZone = ListZone,
	FishingGuide = FishingGuide,
	ListDetails = ListDetails,
   SkillTypes = SkillTypes
}